#!/bin/bash
sudo rm -f systemd-genie/usr/bin/*

# Build genie
pushd genie
dotnet publish -c Release -r linux-x64 --self-contained false
mkdir -p ../systemd-genie/usr/bin/
cp bin/Release/netcoreapp3.0/linux-x64/publish/genie ../systemd-genie/usr/bin/
cp bin/Release/netcoreapp3.0/linux-x64/publish/*.dll ../systemd-genie/usr/bin/
cp bin/Release/netcoreapp3.0/linux-x64/publish/genie.runtimeconfig.json ../systemd-genie/usr/bin/
popd

# Set permissions
sudo chmod -R 0755 systemd-genie/DEBIAN

sudo chown root:root systemd-genie/usr/bin/*
sudo chmod u+s systemd-genie/usr/bin/genie
sudo chmod a+rx systemd-genie/usr/bin/genie

# Compute md5 sums
sudo md5sum systemd-genie/usr/bin/* > systemd-genie/DEBIAN/md5sums
sudo md5sum systemd-genie/lib/genie/* >> systemd-genie/DEBIAN/md5sums
sudo md5sum systemd-genie/lib/systemd/system-environment-generators/* >> systemd-genie/DEBIAN/md5sums

# Build packages
sudo dpkg-deb --build systemd-genie
sudo tar zcvf genie.tar.gz systemd-genie/*
