# If enabled genie to pass the enviroment variables to the genie enviroment
PassEnvironment = true

[PATH]
    # If enabled genie pass all the PATH to the systemd enviroment
    # WARNING: Passing all the path could shadow some apps in systemd 
    PassAllPATH = false
    
    # If enabled genie will pass only some variables that are selected, if enables this
    # overwrite PassAllPATH
    AddCustomPATH = true
    
    # The value to add to the systemd PATH, this could be the whole PATH to pass or value by value
    # Example:
    # AddToPATH = ["/mnt/c/Program Files/VS Code/bin:/mnt/c/Windows"]
    # or
    # AddToPATH = ["/mnt/c/Program Files/VS Code/bin", "/mnt/c/Windows"]
    # If the second method is used dont add : at the end of each value
    AddToPATH = [""]

[ENVIRONMENT]
    # This are the values of the non systemd enviroment to pass to the systemd enviroment
    EnvironmentToPass = ["WSL_DISTRO_NAME", "WSL_INTEROP", "WSLENV"]