#
# This Makefile produces and packages the genie-systemd program.
#

#
# default target: build the executable
#

all:
	gcc genie.c -o genie

#
# clean: delete the package interim files
#

clean:
	rm genie
