#
# This Makefile produces all the binary images.
#

#
# default target: build both for installation
#
build:
	make -C genie-wrapper

#
# clean: clean up after a build/package
#
clean:
	make -C genie-wrapper clean
