name: packaging

on:
  release:
    types: [published]

jobs:
  build-deb:
    runs-on: ubuntu-20.04

    steps:
        
    - name: Install dependencies
      run: sudo apt install devscripts debhelper

    - name: Import GPG Key
      uses: crazy-max/ghaction-import-gpg@v1
      env:
        GPG_PRIVATE_KEY: ${{ secrets.TRANSDEBIAN_REPO_SIGNING_KEY }}
        PASSPHRASE: ${{ secrets.TRANSDEBIAN_REPO_PASSPHRASE }}
    
    - name: Checkout
      uses: actions/checkout@v2
      with:
        ref: ${{ env.GITHUB_REF }}

    - name: Make Binaries
      run: make package-debian
